name: Deploy

on:
  release:
    types: [published]

jobs:

  loopcheck:
    strategy:
      matrix:
        builds: [plain-html,paper,bs4,bs5]
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo ${{ matrix.builds }}
      - uses: actions/checkout@v1
      - name: Compile .css from .scss
        run: |
          rm -rf "./gh-pages-docs/${{ matrix.builds }}"
          mkdir "./gh-pages-docs/${{ matrix.builds }}"
          cat "${{ matrix.builds }}" > "./gh-pages-docs/${{ matrix.builds }}/${{ matrix.builds }}.txt"
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
