name: Deploy

on:
  release:
    types: [published]
    
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Publish report
        run: |
          chmod +x deploy.sh
          ./deploy.sh paper
          ./deploy.sh plain-html
          ./deploy.sh bs4
          ./deploy.sh bs5
