name: Deploy

on:
  release:
    types: [published]

jobs:

  deploy:
    runs-on: [ubuntu-latest]
    steps:  
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          rm -rf "./gh-pages-docs/"
          mkdir -p "./gh-pages-docs/bs5"
          echo "bs5" > "./gh-pages-docs/bs5/bs5.txt"
          mkdir -p "./gh-pages-docs/bs4"
          echo "bs4" > "./gh-pages-docs/bs4/bs4.txt"
          mkdir -p "./gh-pages-docs/plain-html"
          echo "plain-html" > "./gh-pages-docs/plain-html/plain-html.txt"
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: gh-pages-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
